// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class Class
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public DateTime ClassStartAt { get; set; }

    public DateTime ClassFinishAt { get; set; }

    public Guid CourseId { get; set; }

    public Guid? LecturerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ClassAssignment> ClassAssignments { get; set; } = new List<ClassAssignment>();

    public virtual ICollection<ClassMeeting> ClassMeetings { get; set; } = new List<ClassMeeting>();

    public virtual ICollection<ClassQuiz> ClassQuizzes { get; set; } = new List<ClassQuiz>();

    public virtual Course Course { get; set; }

    public virtual User Lecturer { get; set; }

    public virtual ICollection<UserClass> UserClasses { get; set; } = new List<UserClass>();
}