// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassAssignmentSubmission
{
    public Guid Id { get; set; }

    public Guid StudentId { get; set; }

    public Guid AssignmentId { get; set; }

    public string SubmissionText { get; set; }

    public DateTime SubmittedAt { get; set; }

    public string LecturerEvaluation { get; set; }

    public string LecturerNotes { get; set; }

    public Guid? AssignmentSubmissionBundleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ClassAssignment Assignment { get; set; }

    public virtual Bundle AssignmentSubmissionBundle { get; set; }

    public virtual User Student { get; set; }
}