// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassQuiz
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public Guid ClassId { get; set; }

    public bool IsOpen { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<ClassQuizQuestion> ClassQuizQuestions { get; set; } = new List<ClassQuizQuestion>();

    public virtual ICollection<ClassQuizSubmission> ClassQuizSubmissions { get; set; } = new List<ClassQuizSubmission>();
}