// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassQuizQuestion
{
    public Guid Id { get; set; }

    public string Question { get; set; }

    public Guid QuizId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ClassQuizAnswer> ClassQuizAnswers { get; set; } = new List<ClassQuizAnswer>();

    public virtual ClassQuiz Quiz { get; set; }
}