// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassQuizSubmission
{
    public Guid Id { get; set; }

    public Guid QuizId { get; set; }

    public Guid StudentId { get; set; }

    public float Score { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ClassQuiz Quiz { get; set; }

    public virtual User Student { get; set; }
}