// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassQuizAnswer
{
    public Guid Id { get; set; }

    public string Answer { get; set; }

    public bool IsRight { get; set; }

    public Guid QuestionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ClassQuizQuestion Question { get; set; }
}