// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class ClassMeeting
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string MeetingUrl { get; set; }

    public Guid ClassId { get; set; }

    public Guid LecturerId { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Class Class { get; set; }

    public virtual User Lecturer { get; set; }
}