// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class Session
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public DateTime ExpireAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}