// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCampusData.Models;

public partial class UserClass
{
    public Guid Id { get; set; }

    public Guid StudentId { get; set; }

    public Guid ClassId { get; set; }

    public string Evaluation { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Class Class { get; set; }

    public virtual User Student { get; set; }
}